package it.clevercom.echo.sso.model.entity;
// Generated Jan 16, 2017 2:51:50 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoginApplicationId generated by hbm2java
 */
@Embeddable
public class LoginApplicationId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int applicationIdApplication;
	private int loginIdLogin;

	public LoginApplicationId() {
	}

	public LoginApplicationId(int applicationIdApplication, int loginIdLogin) {
		this.applicationIdApplication = applicationIdApplication;
		this.loginIdLogin = loginIdLogin;
	}

	@Column(name = "Application_idApplication", nullable = false)
	public int getApplicationIdApplication() {
		return this.applicationIdApplication;
	}

	public void setApplicationIdApplication(int applicationIdApplication) {
		this.applicationIdApplication = applicationIdApplication;
	}

	@Column(name = "Login_idLogin", nullable = false)
	public int getLoginIdLogin() {
		return this.loginIdLogin;
	}

	public void setLoginIdLogin(int loginIdLogin) {
		this.loginIdLogin = loginIdLogin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginApplicationId))
			return false;
		LoginApplicationId castOther = (LoginApplicationId) other;

		return (this.getApplicationIdApplication() == castOther.getApplicationIdApplication())
				&& (this.getLoginIdLogin() == castOther.getLoginIdLogin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getApplicationIdApplication();
		result = 37 * result + this.getLoginIdLogin();
		return result;
	}

}
