package it.clevercom.echo.rd.model.entity;
// Generated 13-feb-2017 9.08.37 by Hibernate Tools 5.1.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hl7outboundmessage generated by hbm2java
 */
@Entity
@Table(name = "hl7outboundmessage", catalog = "rmdw")
public class Hl7outboundmessage implements java.io.Serializable {

	private Integer id;
	private String messageControlId;
	private String message;
	private String status;
	private String messageType;
	private Date sent;

	public Hl7outboundmessage() {
	}

	public Hl7outboundmessage(String messageControlId, String message, String status, String messageType, Date sent) {
		this.messageControlId = messageControlId;
		this.message = message;
		this.status = status;
		this.messageType = messageType;
		this.sent = sent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "messageControlId", nullable = false)
	public String getMessageControlId() {
		return this.messageControlId;
	}

	public void setMessageControlId(String messageControlId) {
		this.messageControlId = messageControlId;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "messageType", nullable = false, length = 10)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sent", nullable = false, length = 19)
	public Date getSent() {
		return this.sent;
	}

	public void setSent(Date sent) {
		this.sent = sent;
	}

}
