package it.clevercom.echo.rd.model.entity;
// Generated 24-mag-2017 14.48.13 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import it.clevercom.echo.common.jpa.entity.AbstractJpaEchoEntity;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Hl7Patient generated by hbm2java
 */
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name="rd_hl7_patient"
)
public class Hl7Patient  extends AbstractJpaEchoEntity implements java.io.Serializable {


     private Long idhl7patient;
     private Patient patient;
     private String teamIdPatient;
     private String teamAuthorityNsId;
     private String teamAuthorityUid;
     private String teamIdtypecode;
     private String name;
     private String surname;
     private Date dateofbirth;
     private String gender;
     private String residencestreetaddress;
     private String residencecitycode;
     private String residencecountry;
     private String domicilestreetaddress;
     private String domicilecitycode;
     private String domicilecountry;
     private String maritalstatus;
     private String birthplace;
     private String citizenshipid;
     private String citizenshipdesc;
     private Date deathdate;
     private String messagecontrolid;
     private String cfIdPatient;
     private String cfAuthorityNsId;
     private String cfAuthorityUid;
     private String cfIdtypecode;
     private String stpIdPatient;
     private String stpAuthorityNsId;
     private String stpAuthorityUid;
     private String stpIdtypecode;
     private String eniIdPatient;
     private String eniAuthorityNsId;
     private String eniAuthorityUid;
     private String eniIdtypecode;
     private String ccIdPatient;
     private String ccAuthorityNsId;
     private String ccAuthorityUid;
     private String ccIdtypecode;
     private String pkIdPatient;
     private String pkAuthorityNsId;
     private String pkAuthorityUid;
     private String pkIdtypecode;

    public Hl7Patient() {
    }

	
    public Hl7Patient(String messagecontrolid) {
        this.messagecontrolid = messagecontrolid;
    }
    public Hl7Patient(Patient patient, String teamIdPatient, String teamAuthorityNsId, String teamAuthorityUid, String teamIdtypecode, String name, String surname, Date dateofbirth, String gender, String residencestreetaddress, String residencecitycode, String residencecountry, String domicilestreetaddress, String domicilecitycode, String domicilecountry, String maritalstatus, String birthplace, String citizenshipid, String citizenshipdesc, Date deathdate, String messagecontrolid, String cfIdPatient, String cfAuthorityNsId, String cfAuthorityUid, String cfIdtypecode, String stpIdPatient, String stpAuthorityNsId, String stpAuthorityUid, String stpIdtypecode, String eniIdPatient, String eniAuthorityNsId, String eniAuthorityUid, String eniIdtypecode, String ccIdPatient, String ccAuthorityNsId, String ccAuthorityUid, String ccIdtypecode, String pkIdPatient, String pkAuthorityNsId, String pkAuthorityUid, String pkIdtypecode) {
       this.patient = patient;
       this.teamIdPatient = teamIdPatient;
       this.teamAuthorityNsId = teamAuthorityNsId;
       this.teamAuthorityUid = teamAuthorityUid;
       this.teamIdtypecode = teamIdtypecode;
       this.name = name;
       this.surname = surname;
       this.dateofbirth = dateofbirth;
       this.gender = gender;
       this.residencestreetaddress = residencestreetaddress;
       this.residencecitycode = residencecitycode;
       this.residencecountry = residencecountry;
       this.domicilestreetaddress = domicilestreetaddress;
       this.domicilecitycode = domicilecitycode;
       this.domicilecountry = domicilecountry;
       this.maritalstatus = maritalstatus;
       this.birthplace = birthplace;
       this.citizenshipid = citizenshipid;
       this.citizenshipdesc = citizenshipdesc;
       this.deathdate = deathdate;
       this.messagecontrolid = messagecontrolid;
       this.cfIdPatient = cfIdPatient;
       this.cfAuthorityNsId = cfAuthorityNsId;
       this.cfAuthorityUid = cfAuthorityUid;
       this.cfIdtypecode = cfIdtypecode;
       this.stpIdPatient = stpIdPatient;
       this.stpAuthorityNsId = stpAuthorityNsId;
       this.stpAuthorityUid = stpAuthorityUid;
       this.stpIdtypecode = stpIdtypecode;
       this.eniIdPatient = eniIdPatient;
       this.eniAuthorityNsId = eniAuthorityNsId;
       this.eniAuthorityUid = eniAuthorityUid;
       this.eniIdtypecode = eniIdtypecode;
       this.ccIdPatient = ccIdPatient;
       this.ccAuthorityNsId = ccAuthorityNsId;
       this.ccAuthorityUid = ccAuthorityUid;
       this.ccIdtypecode = ccIdtypecode;
       this.pkIdPatient = pkIdPatient;
       this.pkAuthorityNsId = pkAuthorityNsId;
       this.pkAuthorityUid = pkAuthorityUid;
       this.pkIdtypecode = pkIdtypecode;
    }
   
     @GenericGenerator(name="generator", strategy="org.hibernate.id.enhanced.SequenceStyleGenerator", parameters={@Parameter(name="optimizer", value="none"), @Parameter(name="sequence_name", value="hl7patient_id_seq"), @Parameter(name="increment_size", value="1")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="idhl7patient", unique=true, nullable=false)
    public Long getIdhl7patient() {
        return this.idhl7patient;
    }
    
    public void setIdhl7patient(Long idhl7patient) {
        this.idhl7patient = idhl7patient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpatient")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="team-id-patient", length=16)
    public String getTeamIdPatient() {
        return this.teamIdPatient;
    }
    
    public void setTeamIdPatient(String teamIdPatient) {
        this.teamIdPatient = teamIdPatient;
    }

    
    @Column(name="team-authority-ns-id", length=20)
    public String getTeamAuthorityNsId() {
        return this.teamAuthorityNsId;
    }
    
    public void setTeamAuthorityNsId(String teamAuthorityNsId) {
        this.teamAuthorityNsId = teamAuthorityNsId;
    }

    
    @Column(name="team-authority-uid", length=199)
    public String getTeamAuthorityUid() {
        return this.teamAuthorityUid;
    }
    
    public void setTeamAuthorityUid(String teamAuthorityUid) {
        this.teamAuthorityUid = teamAuthorityUid;
    }

    
    @Column(name="team-idtypecode", length=5)
    public String getTeamIdtypecode() {
        return this.teamIdtypecode;
    }
    
    public void setTeamIdtypecode(String teamIdtypecode) {
        this.teamIdtypecode = teamIdtypecode;
    }

    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", length=194)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateofbirth", length=13)
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    
    @Column(name="gender", length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="residencestreetaddress", length=120)
    public String getResidencestreetaddress() {
        return this.residencestreetaddress;
    }
    
    public void setResidencestreetaddress(String residencestreetaddress) {
        this.residencestreetaddress = residencestreetaddress;
    }

    
    @Column(name="residencecitycode", length=50)
    public String getResidencecitycode() {
        return this.residencecitycode;
    }
    
    public void setResidencecitycode(String residencecitycode) {
        this.residencecitycode = residencecitycode;
    }

    
    @Column(name="residencecountry", length=4)
    public String getResidencecountry() {
        return this.residencecountry;
    }
    
    public void setResidencecountry(String residencecountry) {
        this.residencecountry = residencecountry;
    }

    
    @Column(name="domicilestreetaddress", length=120)
    public String getDomicilestreetaddress() {
        return this.domicilestreetaddress;
    }
    
    public void setDomicilestreetaddress(String domicilestreetaddress) {
        this.domicilestreetaddress = domicilestreetaddress;
    }

    
    @Column(name="domicilecitycode", length=50)
    public String getDomicilecitycode() {
        return this.domicilecitycode;
    }
    
    public void setDomicilecitycode(String domicilecitycode) {
        this.domicilecitycode = domicilecitycode;
    }

    
    @Column(name="domicilecountry", length=4)
    public String getDomicilecountry() {
        return this.domicilecountry;
    }
    
    public void setDomicilecountry(String domicilecountry) {
        this.domicilecountry = domicilecountry;
    }

    
    @Column(name="maritalstatus", length=20)
    public String getMaritalstatus() {
        return this.maritalstatus;
    }
    
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }

    
    @Column(name="birthplace", length=250)
    public String getBirthplace() {
        return this.birthplace;
    }
    
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    
    @Column(name="citizenshipid", length=20)
    public String getCitizenshipid() {
        return this.citizenshipid;
    }
    
    public void setCitizenshipid(String citizenshipid) {
        this.citizenshipid = citizenshipid;
    }

    
    @Column(name="citizenshipdesc", length=199)
    public String getCitizenshipdesc() {
        return this.citizenshipdesc;
    }
    
    public void setCitizenshipdesc(String citizenshipdesc) {
        this.citizenshipdesc = citizenshipdesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="deathdate", length=13)
    public Date getDeathdate() {
        return this.deathdate;
    }
    
    public void setDeathdate(Date deathdate) {
        this.deathdate = deathdate;
    }

    
    @Column(name="messagecontrolid", nullable=false)
    public String getMessagecontrolid() {
        return this.messagecontrolid;
    }
    
    public void setMessagecontrolid(String messagecontrolid) {
        this.messagecontrolid = messagecontrolid;
    }

    
    @Column(name="cf-id-patient", length=16)
    public String getCfIdPatient() {
        return this.cfIdPatient;
    }
    
    public void setCfIdPatient(String cfIdPatient) {
        this.cfIdPatient = cfIdPatient;
    }

    
    @Column(name="cf-authority-ns-id", length=20)
    public String getCfAuthorityNsId() {
        return this.cfAuthorityNsId;
    }
    
    public void setCfAuthorityNsId(String cfAuthorityNsId) {
        this.cfAuthorityNsId = cfAuthorityNsId;
    }

    
    @Column(name="cf-authority-uid", length=199)
    public String getCfAuthorityUid() {
        return this.cfAuthorityUid;
    }
    
    public void setCfAuthorityUid(String cfAuthorityUid) {
        this.cfAuthorityUid = cfAuthorityUid;
    }

    
    @Column(name="cf-idtypecode", length=5)
    public String getCfIdtypecode() {
        return this.cfIdtypecode;
    }
    
    public void setCfIdtypecode(String cfIdtypecode) {
        this.cfIdtypecode = cfIdtypecode;
    }

    
    @Column(name="stp-id-patient", length=16)
    public String getStpIdPatient() {
        return this.stpIdPatient;
    }
    
    public void setStpIdPatient(String stpIdPatient) {
        this.stpIdPatient = stpIdPatient;
    }

    
    @Column(name="stp-authority-ns-id", length=20)
    public String getStpAuthorityNsId() {
        return this.stpAuthorityNsId;
    }
    
    public void setStpAuthorityNsId(String stpAuthorityNsId) {
        this.stpAuthorityNsId = stpAuthorityNsId;
    }

    
    @Column(name="stp-authority-uid", length=199)
    public String getStpAuthorityUid() {
        return this.stpAuthorityUid;
    }
    
    public void setStpAuthorityUid(String stpAuthorityUid) {
        this.stpAuthorityUid = stpAuthorityUid;
    }

    
    @Column(name="stp-idtypecode", length=5)
    public String getStpIdtypecode() {
        return this.stpIdtypecode;
    }
    
    public void setStpIdtypecode(String stpIdtypecode) {
        this.stpIdtypecode = stpIdtypecode;
    }

    
    @Column(name="eni-id-patient", length=16)
    public String getEniIdPatient() {
        return this.eniIdPatient;
    }
    
    public void setEniIdPatient(String eniIdPatient) {
        this.eniIdPatient = eniIdPatient;
    }

    
    @Column(name="eni-authority-ns-id", length=20)
    public String getEniAuthorityNsId() {
        return this.eniAuthorityNsId;
    }
    
    public void setEniAuthorityNsId(String eniAuthorityNsId) {
        this.eniAuthorityNsId = eniAuthorityNsId;
    }

    
    @Column(name="eni-authority-uid", length=199)
    public String getEniAuthorityUid() {
        return this.eniAuthorityUid;
    }
    
    public void setEniAuthorityUid(String eniAuthorityUid) {
        this.eniAuthorityUid = eniAuthorityUid;
    }

    
    @Column(name="eni-idtypecode", length=5)
    public String getEniIdtypecode() {
        return this.eniIdtypecode;
    }
    
    public void setEniIdtypecode(String eniIdtypecode) {
        this.eniIdtypecode = eniIdtypecode;
    }

    
    @Column(name="cc-id-patient", length=16)
    public String getCcIdPatient() {
        return this.ccIdPatient;
    }
    
    public void setCcIdPatient(String ccIdPatient) {
        this.ccIdPatient = ccIdPatient;
    }

    
    @Column(name="cc-authority-ns-id", length=20)
    public String getCcAuthorityNsId() {
        return this.ccAuthorityNsId;
    }
    
    public void setCcAuthorityNsId(String ccAuthorityNsId) {
        this.ccAuthorityNsId = ccAuthorityNsId;
    }

    
    @Column(name="cc-authority-uid", length=199)
    public String getCcAuthorityUid() {
        return this.ccAuthorityUid;
    }
    
    public void setCcAuthorityUid(String ccAuthorityUid) {
        this.ccAuthorityUid = ccAuthorityUid;
    }

    
    @Column(name="cc-idtypecode", length=5)
    public String getCcIdtypecode() {
        return this.ccIdtypecode;
    }
    
    public void setCcIdtypecode(String ccIdtypecode) {
        this.ccIdtypecode = ccIdtypecode;
    }

    
    @Column(name="pk-id-patient", length=16)
    public String getPkIdPatient() {
        return this.pkIdPatient;
    }
    
    public void setPkIdPatient(String pkIdPatient) {
        this.pkIdPatient = pkIdPatient;
    }

    
    @Column(name="pk-authority-ns-id", length=20)
    public String getPkAuthorityNsId() {
        return this.pkAuthorityNsId;
    }
    
    public void setPkAuthorityNsId(String pkAuthorityNsId) {
        this.pkAuthorityNsId = pkAuthorityNsId;
    }

    
    @Column(name="pk-authority-uid", length=199)
    public String getPkAuthorityUid() {
        return this.pkAuthorityUid;
    }
    
    public void setPkAuthorityUid(String pkAuthorityUid) {
        this.pkAuthorityUid = pkAuthorityUid;
    }

    
    @Column(name="pk-idtypecode", length=5)
    public String getPkIdtypecode() {
        return this.pkIdtypecode;
    }
    
    public void setPkIdtypecode(String pkIdtypecode) {
        this.pkIdtypecode = pkIdtypecode;
    }




}


