package it.clevercom.echo.rd.model.entity;
// Generated 10-feb-2017 17.38.23 by Hibernate Tools 5.1.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Hl7patientId generated by hbm2java
 */
@Embeddable
public class Hl7patientId implements java.io.Serializable {

	private String idPatientPid3Cx1;
	private String idAuthorityNamespaceIdPid3Cx4Hd1;

	public Hl7patientId() {
	}

	public Hl7patientId(String idPatientPid3Cx1, String idAuthorityNamespaceIdPid3Cx4Hd1) {
		this.idPatientPid3Cx1 = idPatientPid3Cx1;
		this.idAuthorityNamespaceIdPid3Cx4Hd1 = idAuthorityNamespaceIdPid3Cx4Hd1;
	}

	@Column(name = "idPatient-PID3-CX1", nullable = false, length = 16)
	public String getIdPatientPid3Cx1() {
		return this.idPatientPid3Cx1;
	}

	public void setIdPatientPid3Cx1(String idPatientPid3Cx1) {
		this.idPatientPid3Cx1 = idPatientPid3Cx1;
	}

	@Column(name = "idAuthorityNamespaceId-PID3-CX4-HD1", nullable = false, length = 20)
	public String getIdAuthorityNamespaceIdPid3Cx4Hd1() {
		return this.idAuthorityNamespaceIdPid3Cx4Hd1;
	}

	public void setIdAuthorityNamespaceIdPid3Cx4Hd1(String idAuthorityNamespaceIdPid3Cx4Hd1) {
		this.idAuthorityNamespaceIdPid3Cx4Hd1 = idAuthorityNamespaceIdPid3Cx4Hd1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Hl7patientId))
			return false;
		Hl7patientId castOther = (Hl7patientId) other;

		return ((this.getIdPatientPid3Cx1() == castOther.getIdPatientPid3Cx1())
				|| (this.getIdPatientPid3Cx1() != null && castOther.getIdPatientPid3Cx1() != null
						&& this.getIdPatientPid3Cx1().equals(castOther.getIdPatientPid3Cx1())))
				&& ((this.getIdAuthorityNamespaceIdPid3Cx4Hd1() == castOther.getIdAuthorityNamespaceIdPid3Cx4Hd1())
						|| (this.getIdAuthorityNamespaceIdPid3Cx4Hd1() != null
								&& castOther.getIdAuthorityNamespaceIdPid3Cx4Hd1() != null
								&& this.getIdAuthorityNamespaceIdPid3Cx4Hd1()
										.equals(castOther.getIdAuthorityNamespaceIdPid3Cx4Hd1())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdPatientPid3Cx1() == null ? 0 : this.getIdPatientPid3Cx1().hashCode());
		result = 37 * result + (getIdAuthorityNamespaceIdPid3Cx4Hd1() == null ? 0
				: this.getIdAuthorityNamespaceIdPid3Cx4Hd1().hashCode());
		return result;
	}

}
