package it.clevercom.echo.rd.model.entity;
// Generated 13-feb-2017 9.08.37 by Hibernate Tools 5.1.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hl7patient generated by hbm2java
 */
@Entity
@Table(name = "hl7patient", catalog = "rmdw")
public class Hl7patient implements java.io.Serializable {

	private Hl7patientId id;
	private Patient patient;
	private String idAuthorityPid3Cx4Hd2;
	private String idTypeCodePid3Cx5;
	private String namePid5Xpn2;
	private String surnamePid5Xpn1;
	private Date dateOfBirthPid7Ts1;
	private Character genderPid8;
	private String residenceStreetAddressPid11Xad1Sad1;
	private String residenceCityCodePid11Xad3;
	private String residenceCountryPid11Xad6;
	private String domicileStreetAddressPid11Xad1Sad1;
	private String domicileCityCodePid11Xad3;
	private String domicileCountryPid11Xad6;
	private String maritalStatusPid16Ce1;
	private String birthPlacePid23;
	private String citizenshipIdPid26Ce1;
	private String citizenshipDescPid26Ce2;
	private Date deathDatePid29Ts1;
	private String messageControlId;

	public Hl7patient() {
	}

	public Hl7patient(Hl7patientId id, String idAuthorityPid3Cx4Hd2, String idTypeCodePid3Cx5,
			String messageControlId) {
		this.id = id;
		this.idAuthorityPid3Cx4Hd2 = idAuthorityPid3Cx4Hd2;
		this.idTypeCodePid3Cx5 = idTypeCodePid3Cx5;
		this.messageControlId = messageControlId;
	}

	public Hl7patient(Hl7patientId id, Patient patient, String idAuthorityPid3Cx4Hd2, String idTypeCodePid3Cx5,
			String namePid5Xpn2, String surnamePid5Xpn1, Date dateOfBirthPid7Ts1, Character genderPid8,
			String residenceStreetAddressPid11Xad1Sad1, String residenceCityCodePid11Xad3,
			String residenceCountryPid11Xad6, String domicileStreetAddressPid11Xad1Sad1,
			String domicileCityCodePid11Xad3, String domicileCountryPid11Xad6, String maritalStatusPid16Ce1,
			String birthPlacePid23, String citizenshipIdPid26Ce1, String citizenshipDescPid26Ce2,
			Date deathDatePid29Ts1, String messageControlId) {
		this.id = id;
		this.patient = patient;
		this.idAuthorityPid3Cx4Hd2 = idAuthorityPid3Cx4Hd2;
		this.idTypeCodePid3Cx5 = idTypeCodePid3Cx5;
		this.namePid5Xpn2 = namePid5Xpn2;
		this.surnamePid5Xpn1 = surnamePid5Xpn1;
		this.dateOfBirthPid7Ts1 = dateOfBirthPid7Ts1;
		this.genderPid8 = genderPid8;
		this.residenceStreetAddressPid11Xad1Sad1 = residenceStreetAddressPid11Xad1Sad1;
		this.residenceCityCodePid11Xad3 = residenceCityCodePid11Xad3;
		this.residenceCountryPid11Xad6 = residenceCountryPid11Xad6;
		this.domicileStreetAddressPid11Xad1Sad1 = domicileStreetAddressPid11Xad1Sad1;
		this.domicileCityCodePid11Xad3 = domicileCityCodePid11Xad3;
		this.domicileCountryPid11Xad6 = domicileCountryPid11Xad6;
		this.maritalStatusPid16Ce1 = maritalStatusPid16Ce1;
		this.birthPlacePid23 = birthPlacePid23;
		this.citizenshipIdPid26Ce1 = citizenshipIdPid26Ce1;
		this.citizenshipDescPid26Ce2 = citizenshipDescPid26Ce2;
		this.deathDatePid29Ts1 = deathDatePid29Ts1;
		this.messageControlId = messageControlId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPatientPid3Cx1", column = @Column(name = "idPatient-PID3-CX1", nullable = false, length = 16)),
			@AttributeOverride(name = "idAuthorityNamespaceIdPid3Cx4Hd1", column = @Column(name = "idAuthorityNamespaceId-PID3-CX4-HD1", nullable = false, length = 20)) })
	public Hl7patientId getId() {
		return this.id;
	}

	public void setId(Hl7patientId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPatient")
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "idAuthority-PID3-CX4-HD2", nullable = false, length = 199)
	public String getIdAuthorityPid3Cx4Hd2() {
		return this.idAuthorityPid3Cx4Hd2;
	}

	public void setIdAuthorityPid3Cx4Hd2(String idAuthorityPid3Cx4Hd2) {
		this.idAuthorityPid3Cx4Hd2 = idAuthorityPid3Cx4Hd2;
	}

	@Column(name = "idTypeCode-PID3-CX5", nullable = false, length = 5)
	public String getIdTypeCodePid3Cx5() {
		return this.idTypeCodePid3Cx5;
	}

	public void setIdTypeCodePid3Cx5(String idTypeCodePid3Cx5) {
		this.idTypeCodePid3Cx5 = idTypeCodePid3Cx5;
	}

	@Column(name = "name-PID5-XPN2", length = 30)
	public String getNamePid5Xpn2() {
		return this.namePid5Xpn2;
	}

	public void setNamePid5Xpn2(String namePid5Xpn2) {
		this.namePid5Xpn2 = namePid5Xpn2;
	}

	@Column(name = "surname-PID5-XPN1", length = 194)
	public String getSurnamePid5Xpn1() {
		return this.surnamePid5Xpn1;
	}

	public void setSurnamePid5Xpn1(String surnamePid5Xpn1) {
		this.surnamePid5Xpn1 = surnamePid5Xpn1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateOfBirth-PID7-TS1", length = 10)
	public Date getDateOfBirthPid7Ts1() {
		return this.dateOfBirthPid7Ts1;
	}

	public void setDateOfBirthPid7Ts1(Date dateOfBirthPid7Ts1) {
		this.dateOfBirthPid7Ts1 = dateOfBirthPid7Ts1;
	}

	@Column(name = "gender-PID8", length = 1)
	public Character getGenderPid8() {
		return this.genderPid8;
	}

	public void setGenderPid8(Character genderPid8) {
		this.genderPid8 = genderPid8;
	}

	@Column(name = "residenceStreetAddress-PID11-XAD1-SAD1", length = 120)
	public String getResidenceStreetAddressPid11Xad1Sad1() {
		return this.residenceStreetAddressPid11Xad1Sad1;
	}

	public void setResidenceStreetAddressPid11Xad1Sad1(String residenceStreetAddressPid11Xad1Sad1) {
		this.residenceStreetAddressPid11Xad1Sad1 = residenceStreetAddressPid11Xad1Sad1;
	}

	@Column(name = "residenceCityCode-PID11-XAD3", length = 50)
	public String getResidenceCityCodePid11Xad3() {
		return this.residenceCityCodePid11Xad3;
	}

	public void setResidenceCityCodePid11Xad3(String residenceCityCodePid11Xad3) {
		this.residenceCityCodePid11Xad3 = residenceCityCodePid11Xad3;
	}

	@Column(name = "residenceCountry-PID11-XAD6", length = 4)
	public String getResidenceCountryPid11Xad6() {
		return this.residenceCountryPid11Xad6;
	}

	public void setResidenceCountryPid11Xad6(String residenceCountryPid11Xad6) {
		this.residenceCountryPid11Xad6 = residenceCountryPid11Xad6;
	}

	@Column(name = "domicileStreetAddress-PID11-XAD1-SAD1", length = 120)
	public String getDomicileStreetAddressPid11Xad1Sad1() {
		return this.domicileStreetAddressPid11Xad1Sad1;
	}

	public void setDomicileStreetAddressPid11Xad1Sad1(String domicileStreetAddressPid11Xad1Sad1) {
		this.domicileStreetAddressPid11Xad1Sad1 = domicileStreetAddressPid11Xad1Sad1;
	}

	@Column(name = "domicileCityCode-PID11-XAD3", length = 50)
	public String getDomicileCityCodePid11Xad3() {
		return this.domicileCityCodePid11Xad3;
	}

	public void setDomicileCityCodePid11Xad3(String domicileCityCodePid11Xad3) {
		this.domicileCityCodePid11Xad3 = domicileCityCodePid11Xad3;
	}

	@Column(name = "domicileCountry-PID11-XAD6", length = 4)
	public String getDomicileCountryPid11Xad6() {
		return this.domicileCountryPid11Xad6;
	}

	public void setDomicileCountryPid11Xad6(String domicileCountryPid11Xad6) {
		this.domicileCountryPid11Xad6 = domicileCountryPid11Xad6;
	}

	@Column(name = "maritalStatus-PID16-CE1", length = 20)
	public String getMaritalStatusPid16Ce1() {
		return this.maritalStatusPid16Ce1;
	}

	public void setMaritalStatusPid16Ce1(String maritalStatusPid16Ce1) {
		this.maritalStatusPid16Ce1 = maritalStatusPid16Ce1;
	}

	@Column(name = "birthPlace-PID23", length = 250)
	public String getBirthPlacePid23() {
		return this.birthPlacePid23;
	}

	public void setBirthPlacePid23(String birthPlacePid23) {
		this.birthPlacePid23 = birthPlacePid23;
	}

	@Column(name = "citizenshipId-PID26-CE1", length = 20)
	public String getCitizenshipIdPid26Ce1() {
		return this.citizenshipIdPid26Ce1;
	}

	public void setCitizenshipIdPid26Ce1(String citizenshipIdPid26Ce1) {
		this.citizenshipIdPid26Ce1 = citizenshipIdPid26Ce1;
	}

	@Column(name = "citizenshipDesc-PID26-CE2", length = 199)
	public String getCitizenshipDescPid26Ce2() {
		return this.citizenshipDescPid26Ce2;
	}

	public void setCitizenshipDescPid26Ce2(String citizenshipDescPid26Ce2) {
		this.citizenshipDescPid26Ce2 = citizenshipDescPid26Ce2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deathDate-PID29-TS1", length = 10)
	public Date getDeathDatePid29Ts1() {
		return this.deathDatePid29Ts1;
	}

	public void setDeathDatePid29Ts1(Date deathDatePid29Ts1) {
		this.deathDatePid29Ts1 = deathDatePid29Ts1;
	}

	@Column(name = "messageControlId", nullable = false)
	public String getMessageControlId() {
		return this.messageControlId;
	}

	public void setMessageControlId(String messageControlId) {
		this.messageControlId = messageControlId;
	}

}
