package it.clevercom.echo.rd.model.entity;
// Generated 13-feb-2017 9.08.37 by Hibernate Tools 5.1.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "rmdw")
public class Status implements java.io.Serializable {

	private String statusCode;
	private String description;
	private Date created;
	private Date updated;
	private String userUpdate;
	private boolean active;
	private Set<Report> reports = new HashSet<Report>(0);
	private Set<Radiologictask> radiologictasks = new HashSet<Radiologictask>(0);
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<Worklist> worklists = new HashSet<Worklist>(0);

	public Status() {
	}

	public Status(String statusCode, Date created, Date updated, String userUpdate, boolean active) {
		this.statusCode = statusCode;
		this.created = created;
		this.updated = updated;
		this.userUpdate = userUpdate;
		this.active = active;
	}

	public Status(String statusCode, String description, Date created, Date updated, String userUpdate, boolean active,
			Set<Report> reports, Set<Radiologictask> radiologictasks, Set<Order> orders, Set<Worklist> worklists) {
		this.statusCode = statusCode;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.userUpdate = userUpdate;
		this.active = active;
		this.reports = reports;
		this.radiologictasks = radiologictasks;
		this.orders = orders;
		this.worklists = worklists;
	}

	@Id

	@Column(name = "statusCode", unique = true, nullable = false, length = 100)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "userUpdate", nullable = false, length = 100)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Radiologictask> getRadiologictasks() {
		return this.radiologictasks;
	}

	public void setRadiologictasks(Set<Radiologictask> radiologictasks) {
		this.radiologictasks = radiologictasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Worklist> getWorklists() {
		return this.worklists;
	}

	public void setWorklists(Set<Worklist> worklists) {
		this.worklists = worklists;
	}

}
