package it.clevercom.echo.rd.model.entity;
// Generated 13-feb-2017 9.08.37 by Hibernate Tools 5.1.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Worklisttracking generated by hbm2java
 */
@Entity
@Table(name = "worklisttracking", catalog = "rmdw")
public class Worklisttracking implements java.io.Serializable {

	private Integer idWorklistTracking;
	private Worklist worklist;
	private int idRadiologicalTask;
	private int accessionNumber;
	private String statusCode;
	private String priorityCode;
	private int idService;
	private int idModality;
	private Date scheduledDate;
	private Date executionDate;
	private String studyUuid;
	private Integer studyId;
	private int idUser;
	private Date created;
	private Date updated;
	private String userUpdate;
	private boolean active;

	public Worklisttracking() {
	}

	public Worklisttracking(Worklist worklist, int idRadiologicalTask, int accessionNumber, String statusCode,
			String priorityCode, int idService, int idModality, Date scheduledDate, String studyUuid, int idUser,
			Date created, Date updated, String userUpdate, boolean active) {
		this.worklist = worklist;
		this.idRadiologicalTask = idRadiologicalTask;
		this.accessionNumber = accessionNumber;
		this.statusCode = statusCode;
		this.priorityCode = priorityCode;
		this.idService = idService;
		this.idModality = idModality;
		this.scheduledDate = scheduledDate;
		this.studyUuid = studyUuid;
		this.idUser = idUser;
		this.created = created;
		this.updated = updated;
		this.userUpdate = userUpdate;
		this.active = active;
	}

	public Worklisttracking(Worklist worklist, int idRadiologicalTask, int accessionNumber, String statusCode,
			String priorityCode, int idService, int idModality, Date scheduledDate, Date executionDate,
			String studyUuid, Integer studyId, int idUser, Date created, Date updated, String userUpdate,
			boolean active) {
		this.worklist = worklist;
		this.idRadiologicalTask = idRadiologicalTask;
		this.accessionNumber = accessionNumber;
		this.statusCode = statusCode;
		this.priorityCode = priorityCode;
		this.idService = idService;
		this.idModality = idModality;
		this.scheduledDate = scheduledDate;
		this.executionDate = executionDate;
		this.studyUuid = studyUuid;
		this.studyId = studyId;
		this.idUser = idUser;
		this.created = created;
		this.updated = updated;
		this.userUpdate = userUpdate;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idWorklistTracking", unique = true, nullable = false)
	public Integer getIdWorklistTracking() {
		return this.idWorklistTracking;
	}

	public void setIdWorklistTracking(Integer idWorklistTracking) {
		this.idWorklistTracking = idWorklistTracking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idWorklist", nullable = false)
	public Worklist getWorklist() {
		return this.worklist;
	}

	public void setWorklist(Worklist worklist) {
		this.worklist = worklist;
	}

	@Column(name = "idRadiologicalTask", nullable = false)
	public int getIdRadiologicalTask() {
		return this.idRadiologicalTask;
	}

	public void setIdRadiologicalTask(int idRadiologicalTask) {
		this.idRadiologicalTask = idRadiologicalTask;
	}

	@Column(name = "accessionNumber", nullable = false)
	public int getAccessionNumber() {
		return this.accessionNumber;
	}

	public void setAccessionNumber(int accessionNumber) {
		this.accessionNumber = accessionNumber;
	}

	@Column(name = "statusCode", nullable = false, length = 100)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "priorityCode", nullable = false, length = 100)
	public String getPriorityCode() {
		return this.priorityCode;
	}

	public void setPriorityCode(String priorityCode) {
		this.priorityCode = priorityCode;
	}

	@Column(name = "idService", nullable = false)
	public int getIdService() {
		return this.idService;
	}

	public void setIdService(int idService) {
		this.idService = idService;
	}

	@Column(name = "idModality", nullable = false)
	public int getIdModality() {
		return this.idModality;
	}

	public void setIdModality(int idModality) {
		this.idModality = idModality;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduledDate", nullable = false, length = 19)
	public Date getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "executionDate", length = 19)
	public Date getExecutionDate() {
		return this.executionDate;
	}

	public void setExecutionDate(Date executionDate) {
		this.executionDate = executionDate;
	}

	@Column(name = "studyUuid", nullable = false, length = 100)
	public String getStudyUuid() {
		return this.studyUuid;
	}

	public void setStudyUuid(String studyUuid) {
		this.studyUuid = studyUuid;
	}

	@Column(name = "studyId")
	public Integer getStudyId() {
		return this.studyId;
	}

	public void setStudyId(Integer studyId) {
		this.studyId = studyId;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "userUpdate", nullable = false, length = 100)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
