package it.clevercom.echo.tm.model.entity.gateway;
// Generated 4-mag-2017 22.42.08 by Hibernate Tools 5.2.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import it.clevercom.echo.common.jpa.entity.AbstractJpaEchoEntity;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * GatewayEventBattery generated by hbm2java
 */
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name="tm_gateway_event_battery"
)
public class GatewayEventBattery  extends AbstractJpaEchoEntity implements java.io.Serializable {


     private Long idbattery;
     private GatewayEvent gatewayEvent;
     private int level;

    public GatewayEventBattery() {
    }

    public GatewayEventBattery(GatewayEvent gatewayEvent, int level) {
       this.gatewayEvent = gatewayEvent;
       this.level = level;
    }
   
     @GenericGenerator(name="generator", strategy="org.hibernate.id.enhanced.SequenceStyleGenerator", parameters={@Parameter(name="optimizer", value="none"), @Parameter(name="sequence_name", value="tm_gateway_event_idbattery_seq"), @Parameter(name="increment_size", value="1")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="idbattery", unique=true, nullable=false)
    public Long getIdbattery() {
        return this.idbattery;
    }
    
    public void setIdbattery(Long idbattery) {
        this.idbattery = idbattery;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idevent", nullable=false)
    public GatewayEvent getGatewayEvent() {
        return this.gatewayEvent;
    }
    
    public void setGatewayEvent(GatewayEvent gatewayEvent) {
        this.gatewayEvent = gatewayEvent;
    }

    
    @Column(name="level", nullable=false)
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }




}


