package it.clevercom.echo.tm.model.entity.gateway;
// Generated 4-mag-2017 22.42.08 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import it.clevercom.echo.common.jpa.entity.AbstractJpaEchoEntity;

/**
 * GatewayEvent generated by hbm2java
 */
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name="tm_gateway_event"
)
public class GatewayEvent  extends AbstractJpaEchoEntity implements java.io.Serializable {


     private Long idevent;
     private Date timestamp;
     private String devicetype;
     private String gatewayserialnumber;
     private String pheripheralmac;
     private Date receiveddate;
     private Set<GatewayEventBattery> gatewayEventBatteries = new HashSet<GatewayEventBattery>(0);
     private Set<GatewayEventWeight> gatewayEventWeights = new HashSet<GatewayEventWeight>(0);
     private Set<GatewayEventBloodPressure> gatewayEventBloodPressures = new HashSet<GatewayEventBloodPressure>(0);

    public GatewayEvent() {
    }

    // to remove
    @PrePersist
	public void onPrePersist() {
		this.receiveddate = new Date(System.currentTimeMillis());
	}
	
    public GatewayEvent(String devicetype, String gatewayserialnumber, String pheripheralmac, Date receiveddate) {
        this.devicetype = devicetype;
        this.gatewayserialnumber = gatewayserialnumber;
        this.pheripheralmac = pheripheralmac;
        this.receiveddate = receiveddate;
    }
    public GatewayEvent(String devicetype, String gatewayserialnumber, String pheripheralmac, Date receiveddate, Set<GatewayEventBattery> gatewayEventBatteries, Set<GatewayEventWeight> gatewayEventWeights, Set<GatewayEventBloodPressure> gatewayEventBloodPressures) {
       this.devicetype = devicetype;
       this.gatewayserialnumber = gatewayserialnumber;
       this.pheripheralmac = pheripheralmac;
       this.receiveddate = receiveddate;
       this.gatewayEventBatteries = gatewayEventBatteries;
       this.gatewayEventWeights = gatewayEventWeights;
       this.gatewayEventBloodPressures = gatewayEventBloodPressures;
    }
   
     @GenericGenerator(name="generator", strategy="org.hibernate.id.enhanced.SequenceStyleGenerator", parameters={@Parameter(name="optimizer", value="none"), @Parameter(name="sequence_name", value="tm_gateway_event_idevent_seq"), @Parameter(name="increment_size", value="1")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="idevent", unique=true, nullable=false)
    public Long getIdevent() {
        return this.idevent;
    }
    
    public void setIdevent(Long idevent) {
        this.idevent = idevent;
    }

    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="timestamp", nullable=false, length=29)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    
    @Column(name="devicetype", nullable=false, length=2)
    public String getDevicetype() {
        return this.devicetype;
    }
    
    public void setDevicetype(String devicetype) {
        this.devicetype = devicetype;
    }

    
    @Column(name="gatewayserialnumber", nullable=false)
    public String getGatewayserialnumber() {
        return this.gatewayserialnumber;
    }
    
    public void setGatewayserialnumber(String gatewayserialnumber) {
        this.gatewayserialnumber = gatewayserialnumber;
    }

    
    @Column(name="pheripheralmac", nullable=false)
    public String getPheripheralmac() {
        return this.pheripheralmac;
    }
    
    public void setPheripheralmac(String pheripheralmac) {
        this.pheripheralmac = pheripheralmac;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="receiveddate", nullable=false, length=29)
    public Date getReceiveddate() {
        return this.receiveddate;
    }
    
    public void setReceiveddate(Date receiveddate) {
        this.receiveddate = receiveddate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gatewayEvent")
    public Set<GatewayEventBattery> getGatewayEventBatteries() {
        return this.gatewayEventBatteries;
    }
    
    public void setGatewayEventBatteries(Set<GatewayEventBattery> gatewayEventBatteries) {
        this.gatewayEventBatteries = gatewayEventBatteries;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gatewayEvent")
    public Set<GatewayEventWeight> getGatewayEventWeights() {
        return this.gatewayEventWeights;
    }
    
    public void setGatewayEventWeights(Set<GatewayEventWeight> gatewayEventWeights) {
        this.gatewayEventWeights = gatewayEventWeights;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gatewayEvent")
    public Set<GatewayEventBloodPressure> getGatewayEventBloodPressures() {
        return this.gatewayEventBloodPressures;
    }
    
    public void setGatewayEventBloodPressures(Set<GatewayEventBloodPressure> gatewayEventBloodPressures) {
        this.gatewayEventBloodPressures = gatewayEventBloodPressures;
    }




}


