package it.clevercom.echo.tm.model.entity.gateway;
// Generated 4-mag-2017 22.42.08 by Hibernate Tools 5.2.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import it.clevercom.echo.common.jpa.entity.AbstractJpaEchoEntity;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * GatewayEventWeight generated by hbm2java
 */
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name="tm_gateway_event_weight"
)
public class GatewayEventWeight  extends AbstractJpaEchoEntity implements java.io.Serializable {


     private Long idweight;
     private GatewayEvent gatewayEvent;
     private Long bmi;
     private double height;
     private String uom;
     private double weight;

    public GatewayEventWeight() {
    }

    public GatewayEventWeight(GatewayEvent gatewayEvent, Long bmi, double height, String uom, double weight) {
       this.gatewayEvent = gatewayEvent;
       this.bmi = bmi;
       this.height = height;
       this.uom = uom;
       this.weight = weight;
    }
   
     @GenericGenerator(name="generator", strategy="org.hibernate.id.enhanced.SequenceStyleGenerator", parameters={@Parameter(name="optimizer", value="none"), @Parameter(name="sequence_name", value="tm_gateway_event_idweight_seq"), @Parameter(name="increment_size", value="1")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="idweight", unique=true, nullable=false)
    public Long getIdweight() {
        return this.idweight;
    }
    
    public void setIdweight(Long idweight) {
        this.idweight = idweight;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idevent", nullable=false)
    public GatewayEvent getGatewayEvent() {
        return this.gatewayEvent;
    }
    
    public void setGatewayEvent(GatewayEvent gatewayEvent) {
        this.gatewayEvent = gatewayEvent;
    }

    
    @Column(name="bmi", nullable=false)
    public Long getBmi() {
        return this.bmi;
    }
    
    public void setBmi(Long bmi) {
        this.bmi = bmi;
    }

    
    @Column(name="height", nullable=false, precision=17, scale=17)
    public double getHeight() {
        return this.height;
    }
    
    public void setHeight(double height) {
        this.height = height;
    }

    
    @Column(name="uom", nullable=false, length=10)
    public String getUom() {
        return this.uom;
    }
    
    public void setUom(String uom) {
        this.uom = uom;
    }

    
    @Column(name="weight", nullable=false, precision=17, scale=17)
    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }




}


