package it.clevercom.echo.tm.model.entity;
// Generated 10-gen-2017 15.17.23 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caregiver generated by hbm2java
 */
@Entity
@Table(name = "caregiver", catalog = "tmdw")
public class Caregiver implements java.io.Serializable {

	private Integer idCareGiver;
	private Login login;
	private Municipality municipality;
	private String name;
	private String surname;
	private Character gender;
	private String taxCode;
	private Date birthDate;
	private String nationality;
	private String homeAddress;
	private String phoneNumber;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;
	private Set<PatientCaregiver> patientCaregivers = new HashSet<PatientCaregiver>(0);

	public Caregiver() {
	}

	public Caregiver(Login login, Municipality municipality, Date created, Date updated, boolean active,
			String updateUser) {
		this.login = login;
		this.municipality = municipality;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	public Caregiver(Login login, Municipality municipality, String name, String surname, Character gender,
			String taxCode, Date birthDate, String nationality, String homeAddress, String phoneNumber, Date created,
			Date updated, boolean active, String updateUser, Set<PatientCaregiver> patientCaregivers) {
		this.login = login;
		this.municipality = municipality;
		this.name = name;
		this.surname = surname;
		this.gender = gender;
		this.taxCode = taxCode;
		this.birthDate = birthDate;
		this.nationality = nationality;
		this.homeAddress = homeAddress;
		this.phoneNumber = phoneNumber;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
		this.patientCaregivers = patientCaregivers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCareGiver", unique = true, nullable = false)
	public Integer getIdCareGiver() {
		return this.idCareGiver;
	}

	public void setIdCareGiver(Integer idCareGiver) {
		this.idCareGiver = idCareGiver;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLogin", nullable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMunicipality", nullable = false)
	public Municipality getMunicipality() {
		return this.municipality;
	}

	public void setMunicipality(Municipality municipality) {
		this.municipality = municipality;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", length = 100)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "taxCode", length = 50)
	public String getTaxCode() {
		return this.taxCode;
	}

	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthDate", length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "nationality", length = 100)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "homeAddress", length = 100)
	public String getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	@Column(name = "phoneNumber", length = 100)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false, length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caregiver")
	public Set<PatientCaregiver> getPatientCaregivers() {
		return this.patientCaregivers;
	}

	public void setPatientCaregivers(Set<PatientCaregiver> patientCaregivers) {
		this.patientCaregivers = patientCaregivers;
	}

}
