package it.clevercom.echo.tm.model.entity;
// Generated 10-gen-2017 15.17.23 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clinicreport generated by hbm2java
 */
@Entity
@Table(name = "clinicreport", catalog = "tmdw")
public class Clinicreport implements java.io.Serializable {

	private Integer idClinicReport;
	private Clinicfolder clinicfolder;
	private Detectionplan detectionplan;
	private String name;
	private String description;
	private String reportContent;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;

	public Clinicreport() {
	}

	public Clinicreport(Clinicfolder clinicfolder, String name, Date created, Date updated, boolean active,
			String updateUser) {
		this.clinicfolder = clinicfolder;
		this.name = name;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	public Clinicreport(Clinicfolder clinicfolder, Detectionplan detectionplan, String name, String description,
			String reportContent, Date created, Date updated, boolean active, String updateUser) {
		this.clinicfolder = clinicfolder;
		this.detectionplan = detectionplan;
		this.name = name;
		this.description = description;
		this.reportContent = reportContent;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idClinicReport", unique = true, nullable = false)
	public Integer getIdClinicReport() {
		return this.idClinicReport;
	}

	public void setIdClinicReport(Integer idClinicReport) {
		this.idClinicReport = idClinicReport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idClinicFolder", nullable = false)
	public Clinicfolder getClinicfolder() {
		return this.clinicfolder;
	}

	public void setClinicfolder(Clinicfolder clinicfolder) {
		this.clinicfolder = clinicfolder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDetectionPlan")
	public Detectionplan getDetectionplan() {
		return this.detectionplan;
	}

	public void setDetectionplan(Detectionplan detectionplan) {
		this.detectionplan = detectionplan;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "reportContent")
	public String getReportContent() {
		return this.reportContent;
	}

	public void setReportContent(String reportContent) {
		this.reportContent = reportContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false, length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
