package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "tmdw")
public class Country implements java.io.Serializable {

	private Integer idCountry;
	private String countryName;
	private String countryNicename;
	private String countryIso2;
	private String countryIso3;
	private Integer countryIsoNumCode;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;
	private Set<Region> regions = new HashSet<Region>(0);

	public Country() {
	}

	public Country(Date created, Date updated, boolean active, String updateUser) {
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	public Country(String countryName, String countryNicename, String countryIso2, String countryIso3,
			Integer countryIsoNumCode, Date created, Date updated, boolean active, String updateUser,
			Set<Region> regions) {
		this.countryName = countryName;
		this.countryNicename = countryNicename;
		this.countryIso2 = countryIso2;
		this.countryIso3 = countryIso3;
		this.countryIsoNumCode = countryIsoNumCode;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
		this.regions = regions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCountry", unique = true, nullable = false)
	public Integer getIdCountry() {
		return this.idCountry;
	}

	public void setIdCountry(Integer idCountry) {
		this.idCountry = idCountry;
	}

	@Column(name = "countryName", length = 100)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "countryNicename", length = 100)
	public String getCountryNicename() {
		return this.countryNicename;
	}

	public void setCountryNicename(String countryNicename) {
		this.countryNicename = countryNicename;
	}

	@Column(name = "countryIso2", length = 10)
	public String getCountryIso2() {
		return this.countryIso2;
	}

	public void setCountryIso2(String countryIso2) {
		this.countryIso2 = countryIso2;
	}

	@Column(name = "countryIso3", length = 10)
	public String getCountryIso3() {
		return this.countryIso3;
	}

	public void setCountryIso3(String countryIso3) {
		this.countryIso3 = countryIso3;
	}

	@Column(name = "countryIsoNumCode")
	public Integer getCountryIsoNumCode() {
		return this.countryIsoNumCode;
	}

	public void setCountryIsoNumCode(Integer countryIsoNumCode) {
		this.countryIsoNumCode = countryIsoNumCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false, length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<Region> getRegions() {
		return this.regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

}
