package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetectiontypeMeasurementtypeId generated by hbm2java
 */
@Embeddable
public class DetectiontypeMeasurementtypeId implements java.io.Serializable {

	private int idDetectionType;
	private int idMeasurementType;

	public DetectiontypeMeasurementtypeId() {
	}

	public DetectiontypeMeasurementtypeId(int idDetectionType, int idMeasurementType) {
		this.idDetectionType = idDetectionType;
		this.idMeasurementType = idMeasurementType;
	}

	@Column(name = "idDetectionType", nullable = false)
	public int getIdDetectionType() {
		return this.idDetectionType;
	}

	public void setIdDetectionType(int idDetectionType) {
		this.idDetectionType = idDetectionType;
	}

	@Column(name = "idMeasurementType", unique = true, nullable = false)
	public int getIdMeasurementType() {
		return this.idMeasurementType;
	}

	public void setIdMeasurementType(int idMeasurementType) {
		this.idMeasurementType = idMeasurementType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetectiontypeMeasurementtypeId))
			return false;
		DetectiontypeMeasurementtypeId castOther = (DetectiontypeMeasurementtypeId) other;

		return (this.getIdDetectionType() == castOther.getIdDetectionType())
				&& (this.getIdMeasurementType() == castOther.getIdMeasurementType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDetectionType();
		result = 37 * result + this.getIdMeasurementType();
		return result;
	}

}
