package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DetectiontypeMeasurementtype generated by hbm2java
 */
@Entity
@Table(name = "detectiontype_measurementtype", catalog = "tmdw", uniqueConstraints = @UniqueConstraint(columnNames = "idMeasurementType"))
public class DetectiontypeMeasurementtype implements java.io.Serializable {

	private DetectiontypeMeasurementtypeId id;
	private Detectiontype detectiontype;
	private Measurementtype measurementtype;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;

	public DetectiontypeMeasurementtype() {
	}

	public DetectiontypeMeasurementtype(DetectiontypeMeasurementtypeId id, Detectiontype detectiontype,
			Measurementtype measurementtype, Date created, Date updated, boolean active, String updateUser) {
		this.id = id;
		this.detectiontype = detectiontype;
		this.measurementtype = measurementtype;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDetectionType", column = @Column(name = "idDetectionType", nullable = false)),
			@AttributeOverride(name = "idMeasurementType", column = @Column(name = "idMeasurementType", unique = true, nullable = false)) })
	public DetectiontypeMeasurementtypeId getId() {
		return this.id;
	}

	public void setId(DetectiontypeMeasurementtypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDetectionType", nullable = false, insertable = false, updatable = false)
	public Detectiontype getDetectiontype() {
		return this.detectiontype;
	}

	public void setDetectiontype(Detectiontype detectiontype) {
		this.detectiontype = detectiontype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMeasurementType", unique = true, nullable = false, insertable = false, updatable = false)
	public Measurementtype getMeasurementtype() {
		return this.measurementtype;
	}

	public void setMeasurementtype(Measurementtype measurementtype) {
		this.measurementtype = measurementtype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false, length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
