package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Healthkit generated by hbm2java
 */
@Entity
@Table(name = "healthkit", catalog = "tmdw")
public class Healthkit implements java.io.Serializable {

	private Integer idHealthKit;
	private String name;
	private String description;
	private String serialNumber;
	private Date created;
	private Date updated;
	private boolean active;
	private String userUpdate;
	private Set<HealthkitPatient> healthkitPatients = new HashSet<HealthkitPatient>(0);
	private Set<Healthdevice> healthdevices = new HashSet<Healthdevice>(0);

	public Healthkit() {
	}

	public Healthkit(Date created, Date updated, boolean active, String userUpdate) {
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.userUpdate = userUpdate;
	}

	public Healthkit(String name, String description, String serialNumber, Date created, Date updated, boolean active,
			String userUpdate, Set<HealthkitPatient> healthkitPatients, Set<Healthdevice> healthdevices) {
		this.name = name;
		this.description = description;
		this.serialNumber = serialNumber;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.userUpdate = userUpdate;
		this.healthkitPatients = healthkitPatients;
		this.healthdevices = healthdevices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idHealthKit", unique = true, nullable = false)
	public Integer getIdHealthKit() {
		return this.idHealthKit;
	}

	public void setIdHealthKit(Integer idHealthKit) {
		this.idHealthKit = idHealthKit;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "serialNumber", length = 100)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "userUpdate", nullable = false, length = 100)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "healthkit")
	public Set<HealthkitPatient> getHealthkitPatients() {
		return this.healthkitPatients;
	}

	public void setHealthkitPatients(Set<HealthkitPatient> healthkitPatients) {
		this.healthkitPatients = healthkitPatients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "healthkit")
	public Set<Healthdevice> getHealthdevices() {
		return this.healthdevices;
	}

	public void setHealthdevices(Set<Healthdevice> healthdevices) {
		this.healthdevices = healthdevices;
	}

}
