package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Healthdevice generated by hbm2java
 */
@Entity
@Table(name = "healthdevice", catalog = "tmdw")
public class Healthdevice implements java.io.Serializable {

	private Integer idHealthDevice;
	private Healthdevicetype healthdevicetype;
	private Healthkit healthkit;
	private String serialNumber;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;

	public Healthdevice() {
	}

	public Healthdevice(Healthdevicetype healthdevicetype, Healthkit healthkit, Date created, Date updated,
			boolean active, String updateUser) {
		this.healthdevicetype = healthdevicetype;
		this.healthkit = healthkit;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	public Healthdevice(Healthdevicetype healthdevicetype, Healthkit healthkit, String serialNumber, Date created,
			Date updated, boolean active, String updateUser) {
		this.healthdevicetype = healthdevicetype;
		this.healthkit = healthkit;
		this.serialNumber = serialNumber;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idHealthDevice", unique = true, nullable = false)
	public Integer getIdHealthDevice() {
		return this.idHealthDevice;
	}

	public void setIdHealthDevice(Integer idHealthDevice) {
		this.idHealthDevice = idHealthDevice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idHealthDeviceType", nullable = false)
	public Healthdevicetype getHealthdevicetype() {
		return this.healthdevicetype;
	}

	public void setHealthdevicetype(Healthdevicetype healthdevicetype) {
		this.healthdevicetype = healthdevicetype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idHealthKit", nullable = false)
	public Healthkit getHealthkit() {
		return this.healthkit;
	}

	public void setHealthkit(Healthkit healthkit) {
		this.healthkit = healthkit;
	}

	@Column(name = "serialNumber", length = 100)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false, length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
