package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HealthkitPatient generated by hbm2java
 */
@Entity
@Table(name = "healthkit_patient", catalog = "tmdw")
public class HealthkitPatient implements java.io.Serializable {

	private HealthkitPatientId id;
	private Healthkit healthkit;
	private Patient patient;

	public HealthkitPatient() {
	}

	public HealthkitPatient(HealthkitPatientId id, Healthkit healthkit, Patient patient) {
		this.id = id;
		this.healthkit = healthkit;
		this.patient = patient;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idHealthKit", column = @Column(name = "idHealthKit", nullable = false)),
			@AttributeOverride(name = "idPatient", column = @Column(name = "idPatient", nullable = false)),
			@AttributeOverride(name = "assignmentDate", column = @Column(name = "assignmentDate", length = 19)),
			@AttributeOverride(name = "restitutionDate", column = @Column(name = "restitutionDate", length = 19)),
			@AttributeOverride(name = "created", column = @Column(name = "created", nullable = false, length = 19)),
			@AttributeOverride(name = "updated", column = @Column(name = "updated", nullable = false, length = 19)),
			@AttributeOverride(name = "active", column = @Column(name = "active", nullable = false)),
			@AttributeOverride(name = "updateUser", column = @Column(name = "updateUser", nullable = false, length = 100)) })
	public HealthkitPatientId getId() {
		return this.id;
	}

	public void setId(HealthkitPatientId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idHealthKit", nullable = false, insertable = false, updatable = false)
	public Healthkit getHealthkit() {
		return this.healthkit;
	}

	public void setHealthkit(Healthkit healthkit) {
		this.healthkit = healthkit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPatient", nullable = false, insertable = false, updatable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

}
