package it.clevercom.echo.tm.model.entity;
// Generated 10-gen-2017 15.17.23 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HealthkitPatientId generated by hbm2java
 */
@Embeddable
public class HealthkitPatientId implements java.io.Serializable {

	private int idHealthKit;
	private int idPatient;
	private Date assignmentDate;
	private Date restitutionDate;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;

	public HealthkitPatientId() {
	}

	public HealthkitPatientId(int idHealthKit, int idPatient, Date created, Date updated, boolean active,
			String updateUser) {
		this.idHealthKit = idHealthKit;
		this.idPatient = idPatient;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	public HealthkitPatientId(int idHealthKit, int idPatient, Date assignmentDate, Date restitutionDate, Date created,
			Date updated, boolean active, String updateUser) {
		this.idHealthKit = idHealthKit;
		this.idPatient = idPatient;
		this.assignmentDate = assignmentDate;
		this.restitutionDate = restitutionDate;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	@Column(name = "idHealthKit", nullable = false)
	public int getIdHealthKit() {
		return this.idHealthKit;
	}

	public void setIdHealthKit(int idHealthKit) {
		this.idHealthKit = idHealthKit;
	}

	@Column(name = "idPatient", nullable = false)
	public int getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(int idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "assignmentDate", length = 19)
	public Date getAssignmentDate() {
		return this.assignmentDate;
	}

	public void setAssignmentDate(Date assignmentDate) {
		this.assignmentDate = assignmentDate;
	}

	@Column(name = "restitutionDate", length = 19)
	public Date getRestitutionDate() {
		return this.restitutionDate;
	}

	public void setRestitutionDate(Date restitutionDate) {
		this.restitutionDate = restitutionDate;
	}

	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false, length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HealthkitPatientId))
			return false;
		HealthkitPatientId castOther = (HealthkitPatientId) other;

		return (this.getIdHealthKit() == castOther.getIdHealthKit())
				&& (this.getIdPatient() == castOther.getIdPatient())
				&& ((this.getAssignmentDate() == castOther.getAssignmentDate())
						|| (this.getAssignmentDate() != null && castOther.getAssignmentDate() != null
								&& this.getAssignmentDate().equals(castOther.getAssignmentDate())))
				&& ((this.getRestitutionDate() == castOther.getRestitutionDate())
						|| (this.getRestitutionDate() != null && castOther.getRestitutionDate() != null
								&& this.getRestitutionDate().equals(castOther.getRestitutionDate())))
				&& ((this.getCreated() == castOther.getCreated()) || (this.getCreated() != null
						&& castOther.getCreated() != null && this.getCreated().equals(castOther.getCreated())))
				&& ((this.getUpdated() == castOther.getUpdated()) || (this.getUpdated() != null
						&& castOther.getUpdated() != null && this.getUpdated().equals(castOther.getUpdated())))
				&& (this.isActive() == castOther.isActive())
				&& ((this.getUpdateUser() == castOther.getUpdateUser())
						|| (this.getUpdateUser() != null && castOther.getUpdateUser() != null
								&& this.getUpdateUser().equals(castOther.getUpdateUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdHealthKit();
		result = 37 * result + this.getIdPatient();
		result = 37 * result + (getAssignmentDate() == null ? 0 : this.getAssignmentDate().hashCode());
		result = 37 * result + (getRestitutionDate() == null ? 0 : this.getRestitutionDate().hashCode());
		result = 37 * result + (getCreated() == null ? 0 : this.getCreated().hashCode());
		result = 37 * result + (getUpdated() == null ? 0 : this.getUpdated().hashCode());
		result = 37 * result + (this.isActive() ? 1 : 0);
		result = 37 * result + (getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode());
		return result;
	}

}
