package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meetingrequest generated by hbm2java
 */
@Entity
@Table(name = "meetingrequest", catalog = "tmdw")
public class Meetingrequest implements java.io.Serializable {

	private Integer idMeetingRequest;
	private Patient patient;
	private Physician physician;
	private Boolean approved;
	private String meetingDate;
	private String motivation;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;

	public Meetingrequest() {
	}

	public Meetingrequest(Patient patient, Date created, Date updated, boolean active, String updateUser) {
		this.patient = patient;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	public Meetingrequest(Patient patient, Physician physician, Boolean approved, String meetingDate, String motivation,
			Date created, Date updated, boolean active, String updateUser) {
		this.patient = patient;
		this.physician = physician;
		this.approved = approved;
		this.meetingDate = meetingDate;
		this.motivation = motivation;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMeetingRequest", unique = true, nullable = false)
	public Integer getIdMeetingRequest() {
		return this.idMeetingRequest;
	}

	public void setIdMeetingRequest(Integer idMeetingRequest) {
		this.idMeetingRequest = idMeetingRequest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPatient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPhysician")
	public Physician getPhysician() {
		return this.physician;
	}

	public void setPhysician(Physician physician) {
		this.physician = physician;
	}

	@Column(name = "approved")
	public Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(Boolean approved) {
		this.approved = approved;
	}

	@Column(name = "meetingDate", length = 45)
	public String getMeetingDate() {
		return this.meetingDate;
	}

	public void setMeetingDate(String meetingDate) {
		this.meetingDate = meetingDate;
	}

	@Column(name = "motivation", length = 45)
	public String getMotivation() {
		return this.motivation;
	}

	public void setMotivation(String motivation) {
		this.motivation = motivation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
