package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "tmdw")
public class Message implements java.io.Serializable {

	private Integer idMessage;
	private Patient patient;
	private Physician physician;
	private String message;
	private Date readedByPatient;
	private Date readedByPhysician;
	private String attachmentUrl;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;

	public Message() {
	}

	public Message(Patient patient, Date created, Date updated, boolean active, String updateUser) {
		this.patient = patient;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	public Message(Patient patient, Physician physician, String message, Date readedByPatient, Date readedByPhysician,
			String attachmentUrl, Date created, Date updated, boolean active, String updateUser) {
		this.patient = patient;
		this.physician = physician;
		this.message = message;
		this.readedByPatient = readedByPatient;
		this.readedByPhysician = readedByPhysician;
		this.attachmentUrl = attachmentUrl;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMessage", unique = true, nullable = false)
	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPatient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPhysician")
	public Physician getPhysician() {
		return this.physician;
	}

	public void setPhysician(Physician physician) {
		this.physician = physician;
	}

	@Column(name = "message")
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "readedByPatient", length = 19)
	public Date getReadedByPatient() {
		return this.readedByPatient;
	}

	public void setReadedByPatient(Date readedByPatient) {
		this.readedByPatient = readedByPatient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "readedByPhysician", length = 19)
	public Date getReadedByPhysician() {
		return this.readedByPhysician;
	}

	public void setReadedByPhysician(Date readedByPhysician) {
		this.readedByPhysician = readedByPhysician;
	}

	@Column(name = "attachmentURL")
	public String getAttachmentUrl() {
		return this.attachmentUrl;
	}

	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false, length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
