package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notificationtype generated by hbm2java
 */
@Entity
@Table(name = "notificationtype", catalog = "tmdw")
public class Notificationtype implements java.io.Serializable {

	private Integer idNotificationType;
	private String description;
	private Date created;
	private Date updated;
	private boolean active;
	private String updatedUser;
	private Set<Notification> notifications = new HashSet<Notification>(0);

	public Notificationtype() {
	}

	public Notificationtype(Date created, Date updated, boolean active, String updatedUser) {
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updatedUser = updatedUser;
	}

	public Notificationtype(String description, Date created, Date updated, boolean active, String updatedUser,
			Set<Notification> notifications) {
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updatedUser = updatedUser;
		this.notifications = notifications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idNotificationType", unique = true, nullable = false)
	public Integer getIdNotificationType() {
		return this.idNotificationType;
	}

	public void setIdNotificationType(Integer idNotificationType) {
		this.idNotificationType = idNotificationType;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updatedUser", nullable = false, length = 100)
	public String getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationtype")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

}
