package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NurseOrganizationunitId generated by hbm2java
 */
@Embeddable
public class NurseOrganizationunitId implements java.io.Serializable {

	private int idNurse;
	private int idOrganizationUnit;

	public NurseOrganizationunitId() {
	}

	public NurseOrganizationunitId(int idNurse, int idOrganizationUnit) {
		this.idNurse = idNurse;
		this.idOrganizationUnit = idOrganizationUnit;
	}

	@Column(name = "idNurse", nullable = false)
	public int getIdNurse() {
		return this.idNurse;
	}

	public void setIdNurse(int idNurse) {
		this.idNurse = idNurse;
	}

	@Column(name = "idOrganizationUnit", nullable = false)
	public int getIdOrganizationUnit() {
		return this.idOrganizationUnit;
	}

	public void setIdOrganizationUnit(int idOrganizationUnit) {
		this.idOrganizationUnit = idOrganizationUnit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NurseOrganizationunitId))
			return false;
		NurseOrganizationunitId castOther = (NurseOrganizationunitId) other;

		return (this.getIdNurse() == castOther.getIdNurse())
				&& (this.getIdOrganizationUnit() == castOther.getIdOrganizationUnit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNurse();
		result = 37 * result + this.getIdOrganizationUnit();
		return result;
	}

}
