package it.clevercom.echo.tm.model.entity;
// Generated 10-gen-2017 15.17.23 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientCaregiverId generated by hbm2java
 */
@Embeddable
public class PatientCaregiverId implements java.io.Serializable {

	private int idPatient;
	private int idCareGiver;

	public PatientCaregiverId() {
	}

	public PatientCaregiverId(int idPatient, int idCareGiver) {
		this.idPatient = idPatient;
		this.idCareGiver = idCareGiver;
	}

	@Column(name = "idPatient", nullable = false)
	public int getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(int idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "idCareGiver", nullable = false)
	public int getIdCareGiver() {
		return this.idCareGiver;
	}

	public void setIdCareGiver(int idCareGiver) {
		this.idCareGiver = idCareGiver;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientCaregiverId))
			return false;
		PatientCaregiverId castOther = (PatientCaregiverId) other;

		return (this.getIdPatient() == castOther.getIdPatient())
				&& (this.getIdCareGiver() == castOther.getIdCareGiver());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPatient();
		result = 37 * result + this.getIdCareGiver();
		return result;
	}

}
