package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhysicianPatientId generated by hbm2java
 */
@Embeddable
public class PhysicianPatientId implements java.io.Serializable {

	private int idPhysician;
	private int idPatient;

	public PhysicianPatientId() {
	}

	public PhysicianPatientId(int idPhysician, int idPatient) {
		this.idPhysician = idPhysician;
		this.idPatient = idPatient;
	}

	@Column(name = "idPhysician", nullable = false)
	public int getIdPhysician() {
		return this.idPhysician;
	}

	public void setIdPhysician(int idPhysician) {
		this.idPhysician = idPhysician;
	}

	@Column(name = "idPatient", nullable = false)
	public int getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(int idPatient) {
		this.idPatient = idPatient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhysicianPatientId))
			return false;
		PhysicianPatientId castOther = (PhysicianPatientId) other;

		return (this.getIdPhysician() == castOther.getIdPhysician())
				&& (this.getIdPatient() == castOther.getIdPatient());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPhysician();
		result = 37 * result + this.getIdPatient();
		return result;
	}

}
