package it.clevercom.echo.tm.model.entity;
// Generated 10-gen-2017 15.17.23 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhysicianOrganizationunitId generated by hbm2java
 */
@Embeddable
public class PhysicianOrganizationunitId implements java.io.Serializable {

	private int idPhysician;
	private int idOrganizationUnit;

	public PhysicianOrganizationunitId() {
	}

	public PhysicianOrganizationunitId(int idPhysician, int idOrganizationUnit) {
		this.idPhysician = idPhysician;
		this.idOrganizationUnit = idOrganizationUnit;
	}

	@Column(name = "idPhysician", nullable = false)
	public int getIdPhysician() {
		return this.idPhysician;
	}

	public void setIdPhysician(int idPhysician) {
		this.idPhysician = idPhysician;
	}

	@Column(name = "idOrganizationUnit", nullable = false)
	public int getIdOrganizationUnit() {
		return this.idOrganizationUnit;
	}

	public void setIdOrganizationUnit(int idOrganizationUnit) {
		this.idOrganizationUnit = idOrganizationUnit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhysicianOrganizationunitId))
			return false;
		PhysicianOrganizationunitId castOther = (PhysicianOrganizationunitId) other;

		return (this.getIdPhysician() == castOther.getIdPhysician())
				&& (this.getIdOrganizationUnit() == castOther.getIdOrganizationUnit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPhysician();
		result = 37 * result + this.getIdOrganizationUnit();
		return result;
	}

}
