package it.clevercom.echo.tm.model.entity;
// Generated 10-gen-2017 15.17.23 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Systemeventtype generated by hbm2java
 */
@Entity
@Table(name = "systemeventtype", catalog = "tmdw")
public class Systemeventtype implements java.io.Serializable {

	private Integer idSystemEventType;
	private String description;
	private String action;
	private Date created;
	private Date updated;
	private boolean active;
	private String updatedUser;
	private Set<Systemevent> systemevents = new HashSet<Systemevent>(0);

	public Systemeventtype() {
	}

	public Systemeventtype(Date created, Date updated, boolean active, String updatedUser) {
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updatedUser = updatedUser;
	}

	public Systemeventtype(String description, String action, Date created, Date updated, boolean active,
			String updatedUser, Set<Systemevent> systemevents) {
		this.description = description;
		this.action = action;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updatedUser = updatedUser;
		this.systemevents = systemevents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSystemEventType", unique = true, nullable = false)
	public Integer getIdSystemEventType() {
		return this.idSystemEventType;
	}

	public void setIdSystemEventType(Integer idSystemEventType) {
		this.idSystemEventType = idSystemEventType;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "action")
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updatedUser", nullable = false, length = 100)
	public String getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemeventtype")
	public Set<Systemevent> getSystemevents() {
		return this.systemevents;
	}

	public void setSystemevents(Set<Systemevent> systemevents) {
		this.systemevents = systemevents;
	}

}
