package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Treatmenttask generated by hbm2java
 */
@Entity
@Table(name = "treatmenttask", catalog = "tmdw")
public class Treatmenttask implements java.io.Serializable {

	private Integer idTreatmentTask;
	private Treatmentplan treatmentplan;
	private String description;
	private String type;
	private Boolean completed;
	private Date execution;
	private Date scheduleFrom;
	private Date scheduleTo;
	private String taskUuid;
	private Date created;
	private Date updated;
	private boolean active;
	private String updateUser;

	public Treatmenttask() {
	}

	public Treatmenttask(Treatmentplan treatmentplan, String type, Date created, Date updated, boolean active,
			String updateUser) {
		this.treatmentplan = treatmentplan;
		this.type = type;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	public Treatmenttask(Treatmentplan treatmentplan, String description, String type, Boolean completed,
			Date execution, Date scheduleFrom, Date scheduleTo, String taskUuid, Date created, Date updated,
			boolean active, String updateUser) {
		this.treatmentplan = treatmentplan;
		this.description = description;
		this.type = type;
		this.completed = completed;
		this.execution = execution;
		this.scheduleFrom = scheduleFrom;
		this.scheduleTo = scheduleTo;
		this.taskUuid = taskUuid;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTreatmentTask", unique = true, nullable = false)
	public Integer getIdTreatmentTask() {
		return this.idTreatmentTask;
	}

	public void setIdTreatmentTask(Integer idTreatmentTask) {
		this.idTreatmentTask = idTreatmentTask;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTreatmentPlan", nullable = false)
	public Treatmentplan getTreatmentplan() {
		return this.treatmentplan;
	}

	public void setTreatmentplan(Treatmentplan treatmentplan) {
		this.treatmentplan = treatmentplan;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false, length = 11)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "completed")
	public Boolean getCompleted() {
		return this.completed;
	}

	public void setCompleted(Boolean completed) {
		this.completed = completed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "execution", length = 19)
	public Date getExecution() {
		return this.execution;
	}

	public void setExecution(Date execution) {
		this.execution = execution;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduleFrom", length = 19)
	public Date getScheduleFrom() {
		return this.scheduleFrom;
	}

	public void setScheduleFrom(Date scheduleFrom) {
		this.scheduleFrom = scheduleFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduleTo", length = 19)
	public Date getScheduleTo() {
		return this.scheduleTo;
	}

	public void setScheduleTo(Date scheduleTo) {
		this.scheduleTo = scheduleTo;
	}

	@Column(name = "taskUUID", length = 36)
	public String getTaskUuid() {
		return this.taskUuid;
	}

	public void setTaskUuid(String taskUuid) {
		this.taskUuid = taskUuid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "updateUser", nullable = false, length = 100)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
