package it.clevercom.echo.tm.model.entity;
// Generated 17-gen-2017 15.09.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Worktype generated by hbm2java
 */
@Entity
@Table(name = "worktype", catalog = "tmdw")
public class Worktype implements java.io.Serializable {

	private Integer idWorkType;
	private String name;
	private String description;
	private Date created;
	private Date updated;
	private boolean active;
	private String userUpdate;
	private Set<Worktask> worktasks = new HashSet<Worktask>(0);

	public Worktype() {
	}

	public Worktype(String name, Date created, Date updated, boolean active, String userUpdate) {
		this.name = name;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.userUpdate = userUpdate;
	}

	public Worktype(String name, String description, Date created, Date updated, boolean active, String userUpdate,
			Set<Worktask> worktasks) {
		this.name = name;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.userUpdate = userUpdate;
		this.worktasks = worktasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idWorkType", unique = true, nullable = false)
	public Integer getIdWorkType() {
		return this.idWorkType;
	}

	public void setIdWorkType(Integer idWorkType) {
		this.idWorkType = idWorkType;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "userUpdate", nullable = false, length = 100)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "worktype")
	public Set<Worktask> getWorktasks() {
		return this.worktasks;
	}

	public void setWorktasks(Set<Worktask> worktasks) {
		this.worktasks = worktasks;
	}

}
